require 'cgi'
require 'json'
require 'rest_client'
require 'scrolls'
require 'securerandom'
require 'sinatra/base'

require 'backstop-deploys/config'
require 'backstop-deploys/web'
require 'backstop-deploys/version'
